load "Angle.rb"
load "Average.rb"
load "BlackHole.rb"
load "Circle.rb"
load "Coordinates.rb" 
load "Equality.rb"
load "Exponent.rb"
load "Factorial.rb"
load "Fractions.rb"
load "Googol.rb"
load "Grade.rb"
load "Inequality.rb"
load "Notation.rb"
load "Proportion.rb"
load "Rectangle.rb"
load "RectangularPrism.rb"
load "RightTriangle.rb"
load "Semicircle.rb"
load "Sphere.rb"
load "SystemOfEquations.rb"
load "SystemOFInequalities.rb"
load "Trapezoid.rb"
load "Triangle.rb"
load "TriangularPrism.rb"

class Maths
	def self.help
		puts "Angle"
		puts "Average"
		puts "BlackHole"
		puts "Circle"
		puts "Coordinates" 
		puts "Equality"
		puts "Exponent"
		puts "Factorial"
		puts "Fractions"
		puts "Googol"
		puts "Grade"
		puts "Inequality"
		puts "Notation"
		puts "Proportion"
		puts "Rectangle"
		puts "RectangularPrism"
		puts "RightTriangle"
		puts "Semicircle"
		puts "Sphere"
		puts "SystemOfEquations(not fully functional)"
		puts "SystemOFInequalities(not at all functional)"
		puts "Trapezoid"
		puts "Triangle"
		puts "TriangularPrism"
	end
end